### ISSUE TITLE
add layer shell protocol

### ISSUE THREAD

**Issue by godalming123** [keshto/tinywl_plus#4]
I believe this is necersarry for a compositor

**Comment by keshto** [comment]
This is a compositor and it does not include that protocol? but, to be more useful with other tools that protocol is useful. Would you be willing to open a PR?

**Comment by godalming123** [comment]
No, currently I have forked DWL to develop a more minimal WM and do not plan on rebasing it off tinyWL so I do not need this and would rathor get my own wayland compositor off the ground first.

**Comment by keshto** [comment]
Cool
