### ISSUE TITLE
Update to wlroots 0.16

### ISSUE THREAD

**Issue by godalming123** [keshto/tinywl_plus#5]
Wlroots 0.15 is outdated and I feel like a wayland compositor using this version is not incredibly useful.

**Comment by keshto** [comment]
Agreed! I am a bit caught up with another project do you mind doing a PR?

**Comment by godalming123** [comment]
I have a fork of tinywl 0.16 [here](https://github.com/godalming123/tinytile) although the name says tinytile I have not yet implemented any features specifically for floating/tiling EG: SSD. This fork adds a few things that aren't present here but it also has a few that still need to be implemented however I am not great with c partially (almost) entirely undocumented wlroots functions. Here is a list of todos:
# Things implemented in tinywl_plus that aren't in this fork:
- SSD
- maximize functionality (as well as edge maximizing)
- positioning new windows centered
# Things implemented in tinywl_plus that are also in this fork:
- cursor pressed move off windows fix
- attaching dialogs to their parents
# Things in this fork that aren't in tinywl_plus
## Things that aren't tested/need improvement
- full screen windows (when you unfullscreen the window size is not restored to the same)
- a currently broken implementation of drag icons (I have no idea why it does not work and crashes the compositor when you don't hover any clients)
- add a way to focus previous (implementation behaves weirdly)
- add the virtual keyboard protocol (untested)
## Things that are done
- use only alt and alt with other keys bindings together (currently pressing alt opens up a help menu in alacritty)
- configure pointers with libinput for mouse acceleration
- add a keybinding to kill the focused client
- add VT switching support
- use meson as build system instead of make
- when you kill a window the cursor now updates to what it should be
- allow dragging/resizing windows with alt + mouse
- when you kill a window the previous window is focused
- add a `.clang-format` file
- when you move a popup instead move it's parent
- when you focus a parent instead focus it's popup

**Comment by keshto** [comment]
Well you can try to grab tinywl from 0.16 and apply the patches one by one and fix them if at all needed and open a PR against here. Thanks
