### ISSUE TITLE
Thanks for background colour code and Credit.

### ISSUE THREAD

**Issue by lidgnulinux** [keshto/tinywl_plus#7]
It's not an issue and I will close it once it's posted. Hello, I'm also tinkering tinywl and I took some parts of your code, mainly for background color. I put your name on CREDIT. Link : https://gitlab.com/lidgnulinux/tinywl-next/-/blob/main/CREDIT.md

Thanks,
A. Raniri.

**Comment by keshto** [comment]
Thanks :heart:  and glad it helped!
