### ISSUE TITLE
Give focus to previous focused window after closing a window.

### ISSUE THREAD

**Issue by lidgnulinux** [keshto/tinywl_plus#8]
Hello keshto.

I have a question. By default, tinywl won't give focus to previous window (if any) after we close a window. Do you know how to make tinywl give that focus to previous window after we close a window ? AFAIK, it's probably at `xdg_toplevel_unmap` function.

No need to rush to answer this question.
Thanks.

**Comment by keshto** [comment]
the `focus_view` function https://github.com/keshto/tinywl_plus/blob/main/tinywl.c#L205 would give focus as shown here https://github.com/keshto/tinywl_plus/blob/main/tinywl.c#L1154. I am pretty sure it gives focus to previous window but I might be mistaken. Please make a PR to fix it. Yes it would be in the unmap https://github.com/keshto/tinywl_plus/blob/main/tinywl.c#L1157

**Comment by lidgnulinux** [comment]
Well, I'll give it a try.

Thanks @keshto .

**Comment by lidgnulinux** [comment]
Thanks, I found interesting [reference](https://github.com/godalming123/tinytile/tree/0.16.x) and I guess it's will applicable.

**Comment by lidgnulinux** [comment]
Solved. Thanks.
